### PR TITLE
Complete Interface Update Including Main Features

### PR DESCRIPTION
**Pull request by maricarol3355**
Site: https://im-step.uc.r.appspot.com
Homepage includes Book Links, Notes page, Video Display, Calendar Display, and Learner Level Display.
Navigation Bar includes: Home Page, User Guide Page, Settings Page, and Feedback Page

### CODE REVIEW

**Comment by maricarol3355** [comment]
@ptai7 I can deploy. I wasn't sure if I should yet but I'll do it right now

**Comment by maricarol3355** [comment]
Update Pull Request Description. Deployed site is: https://im-step.uc.r.appspot.com

**Comment by maricarol3355** [comment]
@ptai7 After the investigating with the Pod, it seems like I am in need of CJ's upcoming PR to fix this issue. Is it possible for us to push this pull request to minimize the merge conflicts he may have with his future PR?

**Comment by ptai7** [comment]
Noted, approving this CL with the understanding that the Books API will be integrated in the next PR.

**Pull request merged**
